server/docs/pull_request_template.md
This PR corresponds to adding a PR template within the repository.
=> docs: pull request templated added.

server/app/db.py, server/app/main.py, server/masked_sample_questions_and_queries/masked_hotel_schema.json, server/nltk_downloader.py, server/requirements.txt, server/sample_questions_and_queries/hotel_schema.json, server/utilities/config.py, server/utilities/constants/response_messages.py, server/utilities/prompts/base_prompt.py, server/utilities/utility_functions.py
This PR corresponds to the following [CON-25](https://linear.app/conradlabs/issue/CON-25/develop-a-module-for-query-masking)
- Implemented function to mask questions.
- Implemented function to mask SQL queries.
- Created a wrapper function for generating masked JSON from sample questions and queries.
Other updates:
- Moved sample questions and queries folder to the main app directory.
- Added database name to the configuration file.
=> Feat: Create Masking Functions

server/utilities/constants/response_messages.py, server/utilities/prompts/base_prompt.py, server/utilities/vectorize.py
This PR corresponds to the following [Integrate Query Similarity-Based Example Retrieval in Few-Shot Prompts](https://www.notion.so/conradlabshq/Integrate-Query-Similarity-Based-Example-Retrieval-in-Few-Shot-Prompts-0caf682ea2864cdd8a6ee9206942b1c6?pvs=4).
This PR updates the base prompt class to integrate the `fetch_few_shots` and `vectorize_data_samples` methods for loading examples in few-shot prompts.
=> Feat: Integrate Query Similarity-Based Example Retrieval in Few-Shot Prompts

client/src/components/ConfigurationPanel/ConfigurationPanel.js, client/src/pages/Text2Sql/Text2SQL.js
This PR corresponds to the following [Refactor Axios request to use serverUrl from .env](https://www.notion.so/conradlabshq/Refactor-Axios-request-to-use-serverUrl-from-env-439d8c48f0634f5ca6a2d7e285b2f372?pvs=4)
The change replaces the hardcoded URL in the Axios POST request with a dynamically loaded URL from the .env file.
=> Refactor: Update Axios request to use serverUrl from .env

client/src/components/PreviewModal/PreviewModal.js
This PR adds the missing PreviewModal.js file that was intended to be pushed in the previous commit but was forgotten. No additional changes have been made.
=> Fix: Push Missing PreviewModal.js Fille

client/src/constants/databaseEnums.js, server/app/main.py, server/app/request_schema.py, server/data/sample_questions_and_queries/formula_1_schema.json, server/services/anthropic_client.py, server/services/base_client.py, server/services/client_factory.py, server/services/openai_client.py, server/utilities/batch_job.py, server/utilities/config.py, server/utilities/constants/database_enums.py, server/utilities/constants/response_messages.py
This PR corresponds to the following [Explore Batch Jobs In OpenAI](https://www.notion.so/conradlabshq/Explore-Batch-Jobs-In-OpenAI-129512441d3c80dcac9fcc826d181b75?pvs=4)
- Created a utility function file named batch jobs
- Updated openAI client class to have Batch Job related functions
- Added the paths of sample questions and queries, batch input and outputs in config
- Will update the path of sample questions and queries to train questions and queries after train test split is done
=> Feat: Create Batch Jobs

server/app/main.py, server/utilities/constants/LLM_enums.py, server/utilities/constants/response_messages.py, server/utilities/cost_estimation.py
This PR corresponds to the following [Cost Estimation](https://www.notion.so/conradlabshq/Cost-Estimation-42aba19ac0e4418bb9fd358976b663f9?pvs=4)
=> Feat: Implement Cost Estimation

server/scripts/cost_estimation_bird.py, server/scripts/cost_estimation_dataset.py, server/utilities/config.py, server/utilities/constants/response_messages.py, server/utilities/cost_estimation.py
This PR corresponds to the following [Cost Estimation for BIRD Dataset](https://www.notion.so/conradlabshq/Cost-Estimation-for-BIRD-Dataset-5019615762f54d8a821f49834135a899?pvs=4)
This update introduces a script that calculates both the cost and token usage for entire datasets. It supports the following datasets:
- Bird Train
- Bird Dev
- Synthetic Data
Additional Changes:
- Cleaned up config.py by removing unused path variables.
- Commented out print statements in utilities.cost_estimation.py within the calculate_cost_estimate_for_file function.
- This script uses BATCH_INPUT_FILEs as input, which includes generated prompts for the entire dataset. This is not specifically for batch cost estimates, as it provides the total token calculation across the dataset.
=> Feat: Add Cost Estimation Script for Dataset

server/scripts/data_migration_snowflake.py
This PR corresponds to the following [Data Migration of BIRD Datasets to Snowflake](https://www.notion.so/conradlabshq/Data-Migration-of-BIRD-Datasets-to-Snowflake-6ba2e81d9ece48b496909db1e687d542?pvs=4):
Wrote a script to automate the migration process for bird_train and bird_dev.
=> Feat: Data Migration of BIRD Datasets to Snowflake

server/scripts/data_migration_snowflake.py
Updated the migration process to handle partial migrations effectively by addressing individual row errors. 
Uncommented previously deferred code and verified functionality across all identified cases.
Some changes shown is just formatting.
=> Fix (migration): Resolve Row-level Errors for Partial Migrations

server/scripts/evaluate_cortex_analyst.py, server/utilities/constants/script_constants.py
This PR corresponds to the following [Benchmark Baseline Semantic Model](https://www.notion.so/conradlabshq/Benchmark-Baseline-Semantic-Model-160512441d3c80d99c1ed2c22c46610f?pvs=4)
It adds a script that:
- Generates SQL queries using Snowflake’s Cortex Analyst service based on natural language input.
- Compares predicted SQL queries (from Snowflake) with gold standard queries (from SQLite).
- Saves the evaluation results.
=> Feat: Evaluate Cortex Analyst

server/services/base_client.py, server/services/client_factory.py, server/services/google_ai_client.py, server/utilities/config.py, server/utilities/constants/LLM_enums.py
This PR corresponds to the following [Add Google AI as Client ](https://www.notion.so/conradlabshq/Add-Google-AI-as-Client-165512441d3c808ba98af979081575c9?pvs=4)
Implemented a new client for Google AI within the client factory, integrating its models and configurations.
=> Feat: Add Google AI Client and Models

server/scripts/process_dataset_sequentially.py, server/utilities/constants/script_constants.py, server/utilities/utility_functions.py
This PR corresponds to the following [Add Script for Sequential Processing of Dataset](https://www.notion.so/conradlabshq/Add-Script-for-Sequential-Processing-of-Dataset-166512441d3c803db7a6d469ed9199c2?pvs=4)
- This PR introduces a script for sequentially processing datasets. 
- It uses an LLM to generate predicted SQL queries for test data in the dataset. 
- The script initialises or updates metadata, formats SQL responses, generates predictions, compares them with gold SQL queries, and updates metadata with the processing status.
=> Feat: Add Script for Sequential Processing of Dataset

server/scripts/mask_bird.py
Fixed a bug when saving Masked questions
=> Fixed a Bug when saving masked questions

server/scripts/add_descriptions_bird_dataset.py, server/scripts/data_migration_snowflake.py, server/scripts/evaluate_cortex_analyst.py, server/scripts/process_dataset_sequentially.py, server/utilities/config.py, server/utilities/constants/prompts_enums.py, server/utilities/constants/script_constants.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/prompts/prompt_templates.py, server/utilities/utility_functions.py
This PR corresponds to the following [Implement pipeline for creating schema descriptions and improving SQL predictions](https://www.notion.so/conradlabshq/Implement-pipeline-for-creating-schema-descriptions-and-improving-SQL-predictions-17d512441d3c81198c90c61bd421d8e5?pvs=4).  
It adds the ability to generate descriptions for BIRD Dataset schema and an option to improve the predicted sql:  
- Added a script to annotate the BIRD Dataset (dev and train) with descriptions.  
- Updated the utility function to format schemas semantically (Tables, Columns, and Descriptions in YAML format).  
- Added a new prompt combining semantic and full organization formats in `few_shot_prompts.py`.  
- Updated `process_dataset_sequentially.py` to include an option for improving predicted SQL queries.
=> Feat: Pipeline for adding schema descriptions and improving SQL predictions  

server/scripts/process_dataset_sequentially.py, server/services/client_factory.py, server/services/deepseek_client.py, server/utilities/config.py, server/utilities/constants/LLM_enums.py
=> Added DeepSeek Client

server/scripts/process_dataset_sequentially.py, server/scripts/train_test_split_bird.py
We can now set the following config in the main function:
1. Random Split (boolean)
2. Split Size (0-0.99)
3. With Evidence Boolean
=> Add Config to the train test split

server/scripts/process_dataset_sequentially.py, server/scripts/train_test_split_bird.py, server/utilities/generate_schema_used.py
We use code from Chase to generate the schema used in gold sql. We save this in the train and test questions under "schema_used" key for each question
I merged the train test split branch fix here to prevent future merge conflicts.
=> Schema Used in the Gold SQL saved in train test questions

server/scripts/process_dataset_sequentially.py, server/services/client_factory.py, server/utilities/sql_improvement.py
- Created a separate client for handling improvement prompts.
- Moved improvement prompt-related functions to utilities/sql_improvment.py for maintainability.
- Validated Models and their respective LLM before initialising the clients.
=> Fix: Add separate client for Improvement prompt and move Improvment functions to Utilities

server/app/main.py, server/scripts/download_batch_output.py, server/scripts/generate_batch_file.py, server/scripts/process_batch_output.py, server/services/base_client.py, server/services/openai_client.py, server/utilities/batch_job.py, server/utilities/constants/response_messages.py, server/utilities/constants/script_constants.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Refactor-Batch-Scripts-for-Multiple-Candidates-Generation-158512441d3c8039842bd3a2d9c1a0f2?pvs=4)
- Refactored the batch scripts (`generate_batch_file`, `download_batch_output`, `process_batch_output`) to support generating multiple candidates.
- Updated `batch_job.py` utility functions and removed unnecessary validation
- Updated the Batch Job metadata object to follow the following structure:
```
{
"batch_info": {
"dataset_path": "",
"candidates": {
"PromptType1": numOfShots,
.....
},
"model": "",
"temperature": 0,
"max_tokens": 0,
"total_estimated_cost": 0
},
"databases": {
"database1_name": {
"batch_job_id": "",
"state": "",
"estimated_cost": 0
},
.....
}
}
```
=> Refactor: Update batch scripts to support multiple candidates generation

server/scripts/prune_test.py
prune_test uses 2 keys from train and test files:
1. runtime_schema_used
2. schema_used
It compares the 2 and assigns a score between 0 and 1 to measure the accuracy of the schema pruned.
=> Prune Test Compares the gold pruned schema to runtime pruned schema

server/scripts/process_dataset_sequentially.py, server/services/anthropic_client.py, server/services/base_client.py, server/services/deepseek_client.py, server/services/google_ai_client.py, server/services/openai_client.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py
All LLM clients can now query an LLM with chat history. The chat is passed as args to the execute_chat function in each client. The sql_improver now has an additional function that improves upon the sql response with repeatedly giving a chat history to it.
I have also updated the logic of the improver however would like to discuss it further. The improver now goes on to improve until the max_improve_attempts, however if after reaching the max number of attempts the last query is not executable it keeps on trying till a executable query is generated. However, sometimes the model generates the same wrong query repeatedly entering an infinite loop.
Moreover, the deepseek client is implemented but not tested since the api right now generates an error due to ongoing DDOS attacks.
=> Improver Chat Implementation

server/scripts/process_dataset_sequentially.py, server/utilities/m_schema/schema_engine.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/utility_functions.py
format_schema now returns pruned schemas for all format types if matches is passed to it. If matches is passed as None, or not passed it returns the complete schema.
=> Return Pruned Schema for all formats

server/scripts/prune_test.py
We can now test using a boolean on a all DB files or one file.
fixed lower case matching.
=> Fix for prune test

server/scripts/add_runtime_pruned_schema.py, server/utilities/prompts/prompt_templates.py, server/utilities/schema_linking/extract_keyword.py, server/utilities/schema_linking/schema_linking_utils.py
This PR corresponds to the following [Schema Pruning - Column Selector](https://www.notion.so/conradlabshq/Schema-Pruning-Column-Selector-192512441d3c8071a950e604e6afa40e?pvs=4)
This PR introduces a schema selector prompt into the pipeline and adds a new script for generating a pruned schema.
=> Feat: Add Schema Selector Prompt and Pruned Schema Script

server/app/db.py, server/scripts/add_runtime_pruned_schema.py, server/scripts/process_dataset_sequentially.py, server/utilities/m_schema/schema_engine.py, server/utilities/schema_linking/schema_linking_utils.py, server/utilities/utility_functions.py, server/utilities/vectorize.py
For samples and column descriptions the vector db is made for each db once and not per question. Replaced processpool with threadpool to accomodate this.
The first item in add_runtime_pruned_schema is processed without threading so that only one thread makes the lsh and minhashes.
sidequest: small fixes in mschema
=> Vectorize threading fix

server/scripts/add_runtime_pruned_schema.py, server/scripts/prune_test.py, server/scripts/train_test_split_bird.py, server/services/google_ai_client.py, server/utilities/constants/LLM_enums.py, server/utilities/schema_linking/schema_linking_utils.py, server/utilities/schema_linking/value_retrieval.py
It includes minor fixes and improvements related to:
- Improved logic for Schema Pruning, we save some RAM and it is quicker now.
- Adjustments to train/test split logic, test_size was hardcoded.
- Updated prune_test.py to print the dictionary with tab spaces.
- Added BLOCK_NONE threshold to all safety settings in google ai client.
- Added fine tuned schema pruning gemini model
=> Refactor: Minor Fixes in Schema Pruning, Train/Test Split, Google client and and Prune Test

server/utilities/constants/LLM_enums.py
Added the following models:
-  Replaced Gemini 2.0 Flash Experimental with Gemini 2.0 Flash
- Updated Gemini 2.0 Thinking model to a new version
- Added Gemini 2.0 Pro Experimental
- Added Gemini 2.0 Flash Lite Preview
=> Feat: Added New Gemini Models

server/scripts/process_dataset_sequentially.py, server/utilities/candidate_selection.py, server/utilities/prompts/prompt_templates.py
Implemented the selector prompt from XiYan.
=> Implemented Basic XiYan Candidate Selection Prompt

server/scripts/process_dataset_sequentially.py, server/utilities/prompts/base_prompt.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/prompts/zero_shot_prompts.py, server/utilities/vectorize.py
Added evidence in the prompts. Evidence is injected in the get_prompt_class function in process_dataset_sequentially. 
Prompts can be found here: https://docs.google.com/document/d/1flS1Bow2TqFms8YtmR8pKJVuUt4kKczms_wzBGUCnD8/edit?usp=sharing
=> Added evidence

server/app/db.py, server/app/main.py, server/app/request_schema.py, server/scripts/add_descriptions_bird_dataset.py, server/scripts/add_runtime_pruned_schema.py, server/scripts/bird_eval.py, server/scripts/cost_estimation_dataset.py, server/scripts/data_migration_snowflake.py, server/scripts/download_batch_output.py, server/scripts/evaluate_cortex_analyst.py, server/scripts/generate_batch_file.py, server/scripts/process_batch_output.py, server/scripts/process_dataset_sequentially.py, server/scripts/prune_test.py, server/scripts/train_test_split_bird.py, server/services/openai_client.py, server/test/test_main.py, server/utilities/batch_job.py, server/utilities/config.py, server/utilities/constants/script_constants.py, server/utilities/cost_estimation.py, server/utilities/m_schema/schema_engine.py, server/utilities/path_config.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/zero_shot_prompts.py, server/utilities/schema_linking/schema_linking_utils.py, server/utilities/schema_linking/value_retrieval.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py, server/utilities/vectorize.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Change-the-whole-SQL-generation-pipeline-to-get-the-samples-from-Train-and-only-use-Dev-as-Test-192512441d3c806b8cb0ded67240d77a?pvs=4). 
In this change, we:
- Allow train to be used as samples for dev and vice versa.
- Introduce a `PathConfig` class for centralized path management.
- Update all files to use the new configuration.
=> Refactor: Update path config 

server/app/main.py, server/scripts/add_descriptions_bird_dataset.py, server/scripts/process_dataset_sequentially.py, server/utilities/candidate_selection.py, server/utilities/m_schema/schema_engine.py, server/utilities/path_config.py, server/utilities/prompts/base_prompt.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/prompts/zero_shot_prompts.py, server/utilities/schema_linking/schema_linking_utils.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py, server/utilities/vectorize.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Change-the-prompts-to-be-able-to-use-Pruned-Schema-199512441d3c80948449dedeaff8d22b?pvs=4)
- Now generated schema is given to the prompts along with target questions.
- Updated schema-related functions to correctly return the pruned schema for sample questions. 
- Modified the vectorise function to use threading for generating the vectors database.
=> Feat: Integrated Pruned Schema into Our SQL Pipeline

server/utilities/constants/prompts_enums.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py
This PR corresponds to the following [Try ICL Prompt by XiYan](https://www.notion.so/conradlabshq/ICL-Prompt-by-XiYan-188512441d3c8059807fc983efd87414?pvs=4)
Title is description.
=> Feat: Added ICL XiYan Prompt

server/utilities/config.py, server/utilities/vectorize.py
This PR corresponds to the following [Add Persistent ChromaDB client ](https://www.notion.so/conradlabshq/Add-Persistent-ChromaDB-client-19a512441d3c80f8928ee22cb7490f69?pvs=4)
The title is enough description.
=> Refactor: Updated Chromadb Client to Persistent Chromadb client

server/utilities/sql_improvement.py
Fixed small bug where wrong args were being passed to format_schema in xiyan refiner.
=> Fixed Small Bug in Previous merges

server/services/client_factory.py, server/services/dashscope_client.py, server/utilities/config.py, server/utilities/constants/LLM_enums.py
This PR corresponds to the following [Add Alibaba / DashScope Client](https://www.notion.so/conradlabshq/Add-Alibaba-DashScope-Client-1a4512441d3c803a8fcedf403bce2da6?pvs=4)
Implemented Alibaba / DashScope client.
=> Feat: Added Alibaba / DashScope client and Qwen model support

server/scripts/process_dataset_sequentially.py, server/utilities/path_config.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Update-process_dataset_sequentially-to-create-a-single-Prediction-File-19e512441d3c80389f5af357a5c1bd58?pvs=4)
This update enhances process_dataset_sequentially by adding support for generating a single unified prediction file alongside individual prediction files per database.
=> Feat: Support single prediction file in process_dataset_sequentially  

gemini/config.yaml
This PR corresponds to the configuration file for gemini code reviewer
=> Add gemini/config.yaml

gemini/config.yaml, gemini/styleguide.md
Styleguide added for gemini root folder
=> Gemini configuration style guide

gemini/config.yaml
=> Gemini configuration yaml

server/scripts/process_dataset_sequentially.py, server/services/anthropic_client.py, server/services/dashscope_client.py, server/services/deepseek_client.py, server/services/google_ai_client.py, server/services/openai_client.py, server/utilities/constants/prompts_enums.py, server/utilities/prompts/prompt_templates.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py
This PR corresponds to the following [Update SQL Improver to Use Chat-Based LLM Prompting](https://www.notion.so/conradlabshq/Update-SQL-Improver-to-Use-Chat-Based-LLM-Prompting-1a6512441d3c80dc9932edcfd46cea81?pvs=4).
The existing improve_sql_query_chat function currently relied on a single-turn, completion-style prompt to improve SQL queries. Since we are using a chat-based LLM, this update refactors the prompt templates and functions to follow chat format. This includes proper role assignments (system, user, assistant).
=> Feat: Update SQL Improver to Use Chat-Based LLM Prompting

server/preprocess/add_descriptions_bird_dataset.py, server/preprocess/add_runtime_pruned_schema.py, server/preprocess/prepare_sample_dataset.py, server/preprocess/run/run_preprocess_test.sh, server/preprocess/run/run_preprocess_train.sh, server/utilities/config.py, server/utilities/constants/database_enums.py, server/utilities/path_config.py
This PR corresponds to the following tasks: 
- [Prepare Codebase for Preprocessing for BIRD Evaluations](https://www.notion.so/conradlabshq/Prepare-Codebase-for-Preprocessing-for-BIRD-Evaluations-1a6512441d3c80da9880d6fc8aa9fcc2?pvs=4)
- [Update add_descriptions_bird to New column_meaning.json Format](https://www.notion.so/conradlabshq/Update-add_descriptions_bird-to-New-column_meaning-json-Format-1ac512441d3c8050a962f2718f0f8b8d?pvs=4).
Changes:
- Configured environment-based path management in .env
- Added BIRD_TEST DatasetType and updated path_cofig class accordingly
- Added shell scripts for BIRD preprocessing
- `run_preprocess_train.sh` for preprocessing sample dataset
- This adds schema used to train file and descriptions to databases 
- `run_preprocess_test.sh` for preprocessing …
=> Refactor: Prepare Codebase for Preprocessing for BIRD Evaluations

server/utilities/prompts/prompt_templates.py, server/utilities/sql_improvement.py
This PR corresponds to the following [Optimise SQL Refiner by Separating Error Fixing and Query Improvement Prompts](https://www.notion.so/conradlabshq/Optimise-SQL-Refiner-by-Separating-Error-Fixing-and-Query-Improvement-Prompts-1ae512441d3c803092faf25de91d1439?pvs=4)
Introduces a conditional routing mechanism for SQL refinement:
- Queries with errors are sent to the Query Fixer prompt.
- Error-free queries are handled by the Query Refiner prompt.
=> Feat: Optimise SQL Refiner by Separating Error Fixing and Query Improvement Prompts

server/predict_sqls/predict_sqls.py, server/predict_sqls/run/run_predictions.sh
This PR corresponds to the following [Write Predict SQLs Script for BIRD Submission](https://www.notion.so/conradlabshq/Write-Predict-SQLs-Script-for-BIRD-Submission-1a6512441d3c807999e8c344c96fa0b8?pvs=4)
This PR introduces a predict SQLs script for BIRD benchmarking. It includes:
- `predict_sqls.py`: Generates prediction SQLs.
- `run_predictions.sh`: A shell script to execute the prediction script. 
- Using only the necessary processing from `process_dataset_sequentially.py`
=> Feat: Add Predict SQLs Script for BIRD Submission

server/scripts/estimate_costs.py, server/services/openai_client.py, server/utilities/candidate_selection.py, server/utilities/constants/LLM_enums.py, server/utilities/constants/response_messages.py, server/utilities/llm_metrics/deepseek_v3_tokenizer/tokenizer_config.json, server/utilities/llm_metrics/pricing.py, server/utilities/llm_metrics/token_calculator.py, server/utilities/prompts/prompt_templates.py
This PR corresponds to the following [Implement Token Calculator for Token Usage and Pricing Calculation](https://www.notion.so/conradlabshq/Implement-Token-Calculator-for-Token-Usage-and-Pricing-Calculation-1b4512441d3c80c9954ff414bb0af495?pvs=4).  
- Implemented a token calculator component to estimate both token usage and model prices.  
- Added a `pricing.py` module to maintain pricing details for all supported models.  
- Updated models to newer and current models:
- OpenAI ( o3 mini, o1, o1 mini )
- Anthropic ( opus, 3.7 sonnet ) 
- Updated `candidate_selection.py` to have a separate function for prompt generation.
- Introduced a script that calculates the cost for a given test file configuration.  
- `tokenizer_config.json` and `tokenizer.json`are tokenizer files used to estimate …
=> Feat: Add Token and Pricing Estimation

server/utilities/candidate_selection.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Make-GuardRails-for-all-LLM-generation-tasks-1b3512441d3c8039bb73e8f4f57e609c?pvs=4)
Capping SQL generated to 5000 chars,
Capping exec results to 50000 chars, if limit not met then take first x rows, if limit still not met then truncate each row value to y chars.
=> Guard rails

server/preprocess/add_descriptions_bird_dataset.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Edit-add_database_descriptions-to-Handle-Both-Column-Descriptions-and-Description-CSV-1c2512441d3c807486c8d383eb0853e8?pvs=4).
Previously, the `add_descriptions_bird_dataset` updated column descriptions using either the column_meaning.json (new descriptions format for dev & test) or the CSV file (old description format for dev & train). However, for dev datasets, both sources are available, and the function defaulted to using only the CSV file.
This update ensures that when both sources exist, the function selects the more descriptive value between the two.
Changes:
- Compare descriptions from both column_meaning.json and the existing CSV file.
- Retain the longest description for each column.
=> Feat: Edit add_descriptions_bird_dataset to Handle Both Column Descriptions and Description CSV

server/preprocess/add_runtime_pruned_schema.py, server/utilities/prompts/prompt_templates.py, server/utilities/schema_linking/schema_linking_utils.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Update-Codebase-with-Optimised-Schema-Pruning-Prompt-1c2512441d3c80cdbc1ada587024cc9e?pvs=4).
Incorporates the prompt with highest prune score from the schema pruning experiments into the codebase.
Changes:
- Updated `get_relevant_tables_and_columns()` in `schema_linking_utils.py` to reflect the optimised schema pruning prompt.
- Updated `SCHEMA_SELECTOR_PROMPT_TEMPLATE` from `prompt_templates.py`
- Updated the LLM Model to Gemini 2.0 Pro for Schema Pruning in `add_runtime_pruned_schema.py`
The updated prompt is derived from Test 4 in the prune_test sheet of the [Schema Pruning Experiments](https://docs.google.com/spreadsheets/d/1yLYWAyb3rKXI8ZziZF_KXK6mY2EUZsVs0vdNfzcQDLM/edit?usp=sharing).
We will revisit and …
=> Refactor: Update Codebase with Optimised Schema Pruning Prompt

server/utilities/sql_improvement.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Refiner-Improvement-1c3512441d3c80b3aec7cb6340f20385?pvs=4)
The exec results in prompt of the refiner are now in markdown and are randomly sampled
=> Feat: Exec results in Refiner Prompt now randomly sample and in markdown

server/predict_sqls/predict_sqls.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Refactor-SQL-Generation-Pipeline-and-Fix-Schema-Key-Bug-1c2512441d3c80a8aa0fe70cb08a2cda?pvs=4)
This PR addresses a critical issue in the SQL generation pipeline where `schema_used` was incorrectly referenced instead of `runtime_schema_used`. Additionally, the file had accumulated several readability issues over the past few months due to incremental changes, making maintenance difficult.
- Bug Fix:
- Replaced all instances of item['schema_used'] with item['runtime_schema_used'] to ensure correct schema usage during SQL generation and improvement.
- Refactoring & Code Cleanup:
- Improved function organisation / readability.
- Simplified complex nested structures.
- Aligned naming conventions across SQL …
=> Refactor: Fix schema reference bug and improve code readability

README.md
=> Added single line

server/internal_benchmarks/candidate_selection/selection_bench.py, server/internal_benchmarks/refiner/refiner_bench.py
This PR corresponds to the following task: [Selection Bench](https://www.notion.so/conradlabshq/Selection-Bench-1bc512441d3c808499a9fdeb20e5fb9b?pvs=4)
Moved all internal benches to newly created server/internal_benchmarks folder. This now has prune_test, refiner_bench and selection_bench with their respective datasets. 
Created new selection bench to bench the performance of the selector. It uses an already created candidate dataset to evaluate the selector. The bench creates 3 files in the bench_result directory: 
- config_sel.csv: which configs were selected
- correct_sel.csv: if the correct SQL was present in the candidate pool was it selected?
- correct_gen.csv: which candidates generated the correct SQL
=> Candidate Selection Bench

server/scripts/process_dataset_sequentially.py, server/utilities/prompts/base_prompt.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/prompts/zero_shot_prompts.py, server/utilities/selection_metadata_collection.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Refactor-process_dataset_sequentially-py-for-Improved-Code-Quality-and-Consistencyahsa-1d1512441d3c800e9e7be8babfed0836?pvs=4)
This PR refactors process_dataset_sequentially to implement the following:
- Removed selection metadata collection and placed in utilities under selection_metadata_collection.
- Streamlined process_dataset_sequentially to only run for separate DBs and then generate a global prediction file.
Detailed Changes:
process_dataset_sequentially.py
- Introducing `MAX_CANDIDATE_WORKERS` and `MAX_DATABASE_WORKERS`. The latter refers to number of workers that can simultaneously work on candidates and the former refers to the number of workers that can work simultaneously on multiple databases.
- …
=> Refactor process_dataset_sequentially

server/scripts/process_dataset_sequentially.py, server/utilities/constants/LLM_enums.py, server/utilities/prompts/base_prompt.py, server/utilities/prompts/few_shot_prompts.py, server/utilities/prompts/prompt_factory.py, server/utilities/prompts/zero_shot_prompts.py, server/utilities/selection_metadata_collection.py, server/utilities/sql_improvement.py, server/utilities/utility_functions.py
This PR corresponds to the following [Task](https://www.notion.so/conradlabshq/Experiment-with-Backward-Schema-Linking-Approach-for-Improving-Prune-Score-1d1512441d3c8008ad4dd5de16d83479?pvs=4), not directly but as part of backward schema linking this branch had to be updated.
This PR aims to update the `schema-linking` branch with some of the required changes from `main`. These include:
- Addition of new models: `o3-mini`, `o4`, and `gemini 2.5 pro`.
- Database name is now passed as an argument to the `format_schema` and hence `PromptFactory` instead of using a global one from `path_config`.
- Since the `prompt_factory` changed, scripts calling the `prompt_factory` (i.e., `sql_improvement` and `process_dataset_sequentially`) had to be updated. Updating `process_dataset_sequentially` also …
=> Merge Main changes in Schema-Linking

.editorconfig, README.md, server/.pre-commit-config.yaml, server/requirements.txt
This PR corresponds to the following [Integrate-isort-To-Pre-commit-Hook](https://www.notion.so/conradlabshq/Integrate-isort-To-Pre-commit-Hook-1ec512441d3c805cb356de233d3abf96)
We will install each of these packages stated within the `README.md` but one by one, as running these packages will generate alot of code change.
=> feat: add pre-commit hook for pep enforcing packages

README.md, server/.pre-commit-config.yaml, server/services/base_client.py
This PR corresponds to the following [Integrate pydocstyle within repository](https://www.notion.so/conradlabshq/Integrate-pydocstyle-To-Pre-commit-Hook-1ec512441d3c803bae99f87b6ea8ef07)
- feat: add pre-commit hook for pep enforcing packages https://github.com/Conrad-X/text2SQL/pull/114
- feat: isort enforcements results https://github.com/Conrad-X/text2SQL/pull/115 
`server/services/base_client.py` is a dummy file shich I used for self generating the docstrings.
=> feat: added pydocstyle to the repository

README.md
This PR corresponds to the following [Add Coverall Badge](https://www.notion.so/conradlabshq/Badge-Text2SQL-Repository-1ea512441d3c80cc80faf8b145ed4903?pvs=4)
Added Coveralls Badge in README.md
=> Add Coverall Badge
